# Generated by Django 4.2.4 on 2023-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoalWin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
