# Generated by Django 4.2.4 on 2023-09-30 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoalWin', '0003_alter_goal_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='setter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_setter', to=settings.AUTH_USER_MODEL),
        ),
    ]
