# Generated by Django 4.2.4 on 2023-09-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoalWin', '0005_alter_goal_setter_alter_group_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='description',
            new_name='desc',
        ),
    ]
