# Generated by Django 4.2.4 on 2023-10-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoalWin', '0006_rename_description_goal_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
