# Generated by Django 4.2.4 on 2023-10-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoalWin', '0007_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_group', to='GoalWin.group'),
        ),
    ]
