# Generated by Django 4.2.4 on 2023-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoalWin', '0008_alter_goal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
